= Add Cells and Rows

There are multiple ways to group cells into a row.
The cells in a row can be placed on:

[loweralpha]
. <<same,the same line>>
. <<consecutive,consecutive lines>>
. <<mix,a combination of a and b>>

[#same]
== Input a row's cells on the same line

.Cells on the same line
[source]
----
include::example$row.adoc[tag=same]
----

.Result: Rendered table when multiple cells where entered on the same line
====
[width="90"]
include::example$row.adoc[tag=same]
====

[#consecutive]
== Input a row's cells on consecutive lines

When the cells of a row are individually entered on consecutive lines, the `cols` attribute is needed to specify the number of columns in the table.
If the `cols` attribute is not set, the first non-blank line inside the block delimiter (`|===`) determines the number of columns.

.Cells on consecutive, individual lines
[source]
----
include::example$row.adoc[tag=indv-co]
----
<1> The `cols` attribute states that this table has three columns.
The `*` is a repeat operator which is explained in xref:column.adoc#cols-format[column specifiers].

.Result: Rendered table when cells where listed on consecutive, individual lines
====
[width="90"]
include::example$row.adoc[tag=indv]
====

Rows can be formed from adjacent lines of individual cells and cells listed on the same line.

[#mix]
.Cells on the same line and individual lines
[source]
----
include::example$row.adoc[tag=same-indv]
----

.Result: Cells on the same line and individual lines
====
[width="90"]
include::example$row.adoc[tag=same-indv]
====

//The next sections describe and demonstrate the variety of ways you can customize table cells, rows and columns.
