= Align Content by Column

The alignment operators allow you to horizontally and vertically align a column's content.

[#horizontal-operators]
== Horizontal alignment operators

Content can be horizontally aligned to the left or right side of the column as well as the center of the column.

* The less-than symbol (`<`) left aligns the content.
This is the default horizontal alignment.
* The greater-than symbol (`>`) right aligns the content.
* The caret (`+^+`) centers the content.

A horizontal alignment operator is entered in front a <<vertical-operators,vertical alignment operator>> (if present) and in front of a xref:adjust-column-widths.adoc[column's width] unless the multiplier (`+<n>*+`) is used.
A horizontal alignment operator is appended after the multiplier.

* `[cols="2,^1"]` A horizontal alignment operator is placed in front of the column width unless the multiplier is present.
* `[cols=">.^1,2"]` A horizontal alignment operator is placed in front of a vertical alignment operator.
* `[cols="3*>"]` The horizontal alignment operator is placed directly after a multiplier.
* `[cols=">,^"]` When a column width isn't needed, the horizontal alignment operator can represent both the column and the column content's alignment.

=== Center content horizontally in a column

To horizontally center the content in a column, place the `+^+` operator at the beginning of the xref:add-columns.adoc#col-specifier[column's specifier].

[source]
----
[cols="^4,1"]
|===
|This content is horizontally centered.
|Since there isn't a horizontal alignment operator on this column's specifier, the column falls back to the default horizontal alignment.
Content is aligned to the left side of the column by default.
|===
----

The table from the above example is rendered below.

[cols="^4,1"]
|===
|This content is horizontally centered.
|Since there isn't a horizontal alignment operator on this column's specifier, the column falls back to the default horizontal alignment.
Content is aligned to the left side of the column by default.
|===

When the columns are specified using the xref:add-columns.adoc#column-multiplier[multiplier], place the `+^+` operator after the multiplier operator (`+*+`).

[source]
----
[cols="2*^"]
|===
|This content is horizontally centered.
|This content is also horizontally centered.
|===
----

The table from the above example is rendered below.

[cols="2*^"]
|===
|This content is horizontally centered.
|This content is also horizontally centered.
|===

=== Right align content in a column

To align the content in a column to its right side, place the `+>+` operator in front of the column's specifier.

[source]
----
[cols=">4,1"]
|===
|This content is aligned to the right side of the column.
|Since there isn't a horizontal alignment operator on this column's specifier, the column falls back to the default horizontal alignment.
Content is aligned to the left side of the column by default.
|===
----

The table from the above example is rendered below.

[cols=">4,1"]
|===
|This content is aligned to the right side of the column.
|Since there isn't a horizontal alignment operator on this column's specifier, the column falls back to the default horizontal alignment.
Content is aligned to the left side of the column by default.
|===

When the columns are specified using the multiplier, place the `+>+` operator after the xref:add-columns.adoc#column-multiplier[multiplier].

[source]
----
[cols="2*>"]
|===
|This content is aligned to the right side of the column.
|This content is also aligned to the right side of the column.
|===
----

The table from the above example is rendered below.

[cols="2*>"]
|===
|This content is aligned to the right side of the column.
|This content is also aligned to the right side of the column.
|===

[#vertical-operators]
== Vertical alignment operators

Content can be vertically aligned to the top or bottom of a column's cells as well as the center of a column.
Vertical alignment operators begin with a dot (`.`).

* The dot and less-than symbol (`.<`) aligns the content to the top of the column's cells.
This is the default vertical alignment.
* The dot and greater-than symbol (`.>`) aligns the content to the bottom of the column's cells.
* The dot and caret (`+.^+`) centers the content vertically.

Where the vertical alignment operator is placed on a column specifier depends on whether a <<horizontal-operators,horizontal alignment operator>> or a multiplier (`+<n>*+`) is present.

* `[cols="2,.^1"]` A vertical alignment operator is placed in front of the column width unless a multiplier is present.
* `[cols=">.^1,2"]` The vertical alignment operator is placed after the horizontal alignment operator but before the column width.
* `[cols="3*.>"]` The vertical alignment operator is placed after a multiplier.
* `[cols=".^,.>"]` When a column width isn't required, the vertical alignment operator can represent both the column and the column content's alignment.

=== Align content to the bottom of a column's cells

To align the content in a column to the bottom of each cell, place the `+.>+` operator in front of the xref:adjust-column-widths.adoc[column's width].

[source]
----
[cols=".>2,1"]
|===
|This content is vertically aligned to the bottom of the cell.
|There isn't a vertical alignment operator on this column's specifier, so the column falls back to the default vertical alignment.
The content is positioned at the top of the cell by default.
|===
----

The table from the above example is rendered below.

[cols=".>2,1"]
|===
|This content is vertically aligned to the bottom of the cell.
|There isn't a vertical alignment operator on this column's specifier, so the column falls back to the default vertical alignment.
The content is positioned at the top of the cell by default.
|===

=== Center content vertically in a column

To vertically center the content in a column, place the `+.^+` operator in front of the xref:adjust-column-widths.adoc[column's width].

[source]
----
[cols=".^2,1"]
|===
|This content is centered vertically in the cell.
|There isn't a vertical alignment operator on this column's specifier, so the column falls back to the default vertical alignment.
The content is positioned at the top of the cell by default.
|===
----

The table from the above example is rendered below.

[cols=".^2,1"]
|===
|This content is centered vertically in the cell.
|There isn't a vertical alignment operator on this column's specifier, so the column falls back to the default vertical alignment.
The content is positioned at the top of the cell by default.
|===

To vertically align the content to the middle of the cells in all of the columns, add the vertically center operator (`.^`) after the xref:add-columns.adoc#column-multiplier[multiplier].

[source]
----
[cols="2*.^"]
|===
|This content is vertically centered.
|This content is also vertically centered.
|===
----

The table from the above example is rendered below.

[cols="2*.^"]
|===
|This content is centered vertically in the cell.
|This content is also centered vertically in the cell.
|===

== Apply horizontal and vertical alignment operators to the same column

A column can have a vertical and horizontal alignment operator placed on its xref:add-columns.adoc#col-specifier[specifier].
The <<horizontal-operators,horizontal operator>> always precedes the <<vertical-operators,vertical operator>>.
Both operators precede the column width except when a xref:add-columns.adoc#column-multiplier[multiplier] is used, then the operators are placed after the multiplier.

[source]
----
[cols="^.>2,1,>.^1"]
|===
|This content is centered horizontally and aligned to the bottom of the cell.
|There aren't any alignment operators on this column's specifier, so the column falls back to the default alignments.
The default horizontal alignment is the left side of the column.
The default vertical alignment is the top of the cell.
|This content is aligned to the right side of the cell and centered vertically.
|===
----

The table from the above example is rendered below.

[cols="^.>2,1,>.^1"]
|===
|This content is centered horizontally and aligned to the bottom of the cell.
|There aren't any alignment operators on this column's specifier, so the column falls back to the default alignments.
The default horizontal alignment is the left side of the column.
The default vertical alignment is the top of the cell.
|This content is aligned to the right side of the cell and centered vertically.
|===
