= Build a Basic Table

== Table syntax

A table is delimited by a vertical bar and three equal signs (`|===`) and made up of cells.
A cell is specified by a vertical bar (`|`).
The default table data format is PSV (Prefix Separated Values); that means the processor creates a new cell each time it encounters a vertical bar.
Cells are grouped into rows.
Each row must share the same number of cells, taking into account any xref:span.adoc[column or row spans].
Then, each consecutive cell in a row is placed in a separate column.

The table example below consists of two columns and three rows.

[#basic-table]
.Basic table
[source]
----
include::example$table.adoc[tag=base-co]
----
<1> The table's content boundaries are defined by a vertical bar followed by three equal signs (`|===`).
<2> Inserting a blank line before the first row is a trick to ensure the first row is not treated as the table header.
<3> A new cell is marked by a vertical bar (`|`).
<4> Rows can optionally be separated by any number of blank lines.

.Result: Rendered basic table
include::example$table.adoc[tag=base-alt]

Like with all blocks, you can add a role to a table using the `role` attribute.
The role attribute becomes a CSS class when converted to HTML.
The preferred shorthand for assigning the role attribute is to put the role name in the first position of the block attribute list prefixed with a `.` character, as shown here:

[source]
----
include::example$table.adoc[tag=base-rolename]
----

Leading and trailing spaces around cell content is stripped and, therefore, doesn't affect the table's layout when rendered.


////
The two examples below illustrate how leading and trailing spaces don't change the rendered table's layout.

.Cell content adjacent to the |
[source]
----
include::ex-table.adoc[tag=cell1]
----

.Result: Rendered table when cell content was entered adjacent to the |
[width="90"]
include::ex-table.adoc[tag=cell1]

.Cell content with varying leading and trailing spaces
[source]
----
include::ex-table.adoc[tag=cell2]
----

.Result: Rendered table when cell content was bounded by varying leading and trailing spaces
[width="90"]
include::ex-table.adoc[tag=cell2]
////
