= Table Cells

[#cell]
== Cell formatting

In addition to sharing many of the column specifier capabilities, cell specifiers allow cells to span rows and columns.
Like a column specifier, a cell specifier is made up of components.
These components, listed and defined below, are all optional.

* span
* align
* style

A cell specifier is prefixed directly to the cell delimiter (`|`) preceding the content you want to customize.

The span component can duplicate a cell or have it span multiple rows or columns.

== Duplicate cell content

To duplicate a cell in multiple, consecutive columns, prefix the `|` with the multiplication factor and the `+*+` operator.

.Cell duplicated across three columns
[source]
----
include::example$cell.adoc[tag=3dup]
----

.Result: Rendered table where cell was duplicated across three columns
[width="90"]
include::example$cell.adoc[tag=3dup]

== Style cell content

The xref:column.adoc#cols-style[style component] can also be applied to individual cells.
For example, you can apply the AsciiDoc element styles to an individual cell by prefixing the vertical bar with an `a`.

.Comparing cells using AsciiDoc styles and no AsciiDoc styles
[source]
----
include::example$cell.adoc[tag=cell-ad]
----

.Result: Rendered table comparing cells using AsciiDoc styles and no AsciiDoc styles
[width="90"]
include::example$cell.adoc[tag=cell-ad]

Source code listing can be placed inside cells by using the listing syntax.

.Cells with source code listing
....
include::example$cell.adoc[tag=cell-src]
....

.Result: Rendered table with cells containing source code listing
[width="90"]
====
include::example$cell.adoc[tag=cell-src]
====

For the grand finale, let's apply a variety of specifiers to individual cells.

.Building a variety of cell specifiers
[source]
----
include::example$cell.adoc[tag=cell-v]
----

.Result: Rendered table featuring a variety of cell specifiers
[width="90"]
include::example$cell.adoc[tag=cell-v]
