= Getting Started with Tables

== Default table syntax

A table is delimited by a vertical bar and three equal signs (`|===`).
It contains cells that are arranged into rows according to the number of columns the table is assigned.
The number of columns a table contains can be specified implicitly using the number of cells in the table's first row or by setting the `cols` attribute.
Each cell is specified by a vertical bar (`|`).

If you're new to AsciiDoc tables, the xref:build-a-basic-table.adoc[Build a basic table page] provides step by step directions for creating your first table.

== Style and layout options

Table content can be:

* styled and aligned by column or cell,
* aligned by row,
* duplicated across multiple rows, and
* marked up by any AsciiDoc syntax.

Table cells can span rows and columns.

You can adjust a table's:

* width,
* orientation, and
* border style.

You can also specify each column's width and designate header and footer rows.

== Supported data formats

The default table data format is prefix-separated values (PSV); that means the processor creates a new cell each time it encounters a vertical bar (`|`).
AsciiDoc also supports comma-separated values (CSV), tab-separated values (TSV), and delimited data values (DSV).



////
Cells are grouped into rows.
Each row must share the same number of cells, taking into account any xref:span.adoc[column or row spans].
Then, each consecutive cell in a row is placed in a separate column.
////
