= Document Subtitle
// this page has some weird complexity for such a simple thing

Asciidoctor recognizes a subtitle in the xref:title.adoc[document title].

== Subtitle syntax

If the document title (level-0 section heading) contains at least one colon followed by a space (i.e, `:{sp}`), Asciidoctor treats the text after the final colon-space sequence as the subtitle.

NOTE: The subtitle is not distinguished from the document title in the `html5` output.
It's only distinguished from the document title when using the `docbook`, `epub3`, and `pdf` converters.

.A document title that contains a subtitle
[source]
----
= Main Title: Subtitle
----

The separator is searched from the end of the text.
Therefore, only the last occurrence of the separator (i.e, `:{sp}`) is used for partitioning the title.

.A document title that contains a subtitle and more than one separator
[source]
----
= Main Title: Main Title Continued: Subtitle
----

You can modify the title separator by specifying the `separator` block attribute explicitly above the document title.
Note that a space will automatically be appended to the separator value.

.A document title with an explicit title separator
[source]
----
[separator=::]
= Main Title:: Subtitle
----

You can also set the separator using a document attribute, either in the document:

.A document title with an explicit title separator
[source]
----
= Main Title:: Subtitle
:title-separator: ::
----

or from the API or CLI (shown here):

....
$ asciidoctor -a title-separator=:: document.adoc
....

You can partition the title from the API when calling the `doctitle` method on Document:

.Retrieving a partitioned document title
[source,ruby]
----
title_parts = document.doctitle partition: true
puts title_parts.title
puts title_parts.subtitle
----

You can partition the title in an arbitrary way by passing the separator as a value to the partition option.
In this case, the partition option both activates subtitle partitioning and passes in a custom separator.

.Retrieving a partitioned document title with a custom separator
[source,ruby]
----
title_parts = document.doctitle partition: '::'
puts title_parts.title
puts title_parts.subtitle
----

////
.Document with a subtitle
[source]
----
include::example$title.adoc[tag=sub-1]
----

In this example, the following is true:

Main title:: The Dangerous and Thrilling Documentation Chronicles
Subtitle:: A Tale of Caffeine and Words

.Document with a subtitle and multiple colons
[source]
----
include::example$title.adoc[tag=sub-2]
----

In this example, the following is true:

Main title:: A Cautionary Tale: The Dangerous and Thrilling Documentation Chronicles
Subtitle:: A Tale of Caffeine and Words

Instead of using a colon followed by a space as the separator characters between the main title and the subtitle, you can specify a custom separator using the `title-separator` attribute.

.Document with a subtitle using a custom separator
[source]
----
include::example$title.adoc[tag=sub-3]
----

Note that a space is always appended to the value of the `title-separator` (making the default value of the `title-separator` effectively a single colon).

This content needs to be moved or reconsidered:

Asciidoctor also provides an API for extracting the title and subtitle.
See the API docs for the http://www.rubydoc.info/gems/asciidoctor/Asciidoctor/Document/Title[Document::Title] for more information.
Support for subtitle functionality for other sections is being considered.
Refer to https://github.com/asciidoctor/asciidoctor/issues/1493[issue #1493].
////
