= Attribute Assignment Precedence

== Default attribute value precedence

The attribute assignment precedence, listed from highest to lowest, is:

. An attribute passed to the API or CLI
. An attribute defined in the document
. The default value of the attribute, if applicable

Let's use the `doctype` attribute to show how precedence works.

The default value for the `doctype` attribute is `article`.
Therefore, if the `doctype` attribute is not assigned a value (either in the document, API, or CLI), the processor will assign it the default value of `article`.
If the `doctype` attribute is set in the document (i.e., assigned a new value, such as `book`), that value will override the default value.
Finally, if a value is assigned to the `doctype` attribute via the API or CLI, that value will override both the default value and the value assigned in the document.

== Change attribute value precedence

You can adjust the precedence of attribute values passed to the API or CLI by adding the `@` override modifier to the end of the attribute value (or, since 1.5.7, the end of the attribute name).
Adding this modifier lowers the precedence of an attribute (assigned using the API or CLI) so the document can override the value.

Let's update the attribute assignment precedence list defined earlier to reflect this additional rule:

. An attribute passed to the API or CLI whose value does not end in `@`
. An attribute defined in the document
. An attribute passed to the API or CLI whose value (or, since Asciidoctor 1.5.7, name) ends in `@`
. The default value of the attribute, if applicable
