= Attribute Assignment Precedence

== Default attribute value precedence

By default, the attribute assignment precedence, from highest (i.e., overrides all other assigned values) to lowest, is:

. Attribute set and defined via the API or command line
. Attribute set and defined in the document
. Attribute automatically set and defined by default

Let's use the `doctype` attribute to show how precedence works.

Asciidoctor automatically sets the `doctype` attribute and assigns it the default value of `article`.
In other words, if `doctype` isn't set and assigned a value in the document header, API, or from the command line, it will be set and assigned the value `article` at runtime.
However, if `doctype` is set in the document header and assigned the value `book`, `book` will override the default value.
Finally, a value assigned to `doctype` via the API or command line, will overrule a value assigned in the document and the default value.

== Change attribute value precedence

You can adjust the precedence of attribute values assigned via the API or command line.
In the API or CLI, you can add an `@` symbol to the end of an attribute value and make that value assignment have a lower precedence than an assignment in the document.

The API or CLI adjusted precedence, from highest to lowest, is:

. Attribute passed to the API or CLI that does not end in `@`
. Attribute defined in the document
. Attribute passed to the API or CLI that ends in `@`
. Default value
