= Catch Attribute Errors

When you reference a missing or undefined attribute, the entire line that contains the attribute reference is dropped when the document is converted.
You can change this behavior using the `attribute-missing` and `attribute-undefined` attributes.

== Missing attribute 

Attribute-missing controls how missing references are handled.
By default, missing references are left intact so it's clear to the author when one hasn't been satisfied since, likely, the intent is for it to be replaced.

This attribute has four possible values:

`skip`:: leave the reference in place (default setting)
`drop`:: drop the reference, but not the line
`drop-line`:: drop the line on which the reference occurs
`warn`:: print a warning about the missing attribute

Consider the following line:

[source]
Hello, {name}!

Here's how the line is handled in each case, assuming the `name` attribute is not defined:

[horizontal]
`skip`:: Hello, \{name}!
`drop`:: Hello, !
`drop-line`:: {empty}
`warn`::
+
----
 WARNING: skipping reference to missing attribute: XYZ
----

== Undefined attribute

Attribute-undefined controls how expressions that undefine an attribute are handled.
By default, the line is dropped since the expression is a statement, not content.

This attribute has two possible values:

`drop`:: substitute the expression with an empty string after processing it
`drop-line`:: drop the line that contains this expression (default setting and compliant behavior)

The option `skip` doesn't make sense here since the statement is not intended to produce content.

Consider the following declaration:

```
{set:name!}
```

Depending on whether `attribute-undefined` is `drop` or `drop-line`, either the statement or the line that contains it will be discarded.
It's reasonable to stick with the compliant behavior, drop-line, in this case.

TIP: We recommend putting any statement that undefines an attribute on a line by itself.
