= Customize Attribute Substitutions

When Asciidoctor processes a document, it uses a set of six text substitution elements.
xref:subs:substitutions.adoc[Text substitution elements] replace characters, markup, attribute references, and macros with converter-specific styles and values.

The header substitution group, which replaces xref:subs:special-characters.adoc[special characters] and xref:subs:attributes.adoc[attribute references] in text, is applied to the values of attribute entries, regardless of whether the entries are defined in the header or in the document body.
That means that any inline formatting in an attribute value isn't interpreted because:

. inline formatting is not applied when Asciidoctor sets an attribute, and
. inline formatting is not applied when an attribute is referenced since the relevant substitutions come before attributes are resolved.

[#pass-macro]
== Change substitutions when assigning a value

If you want different substitutions to be applied to the value of an attribute entry, you can use the xref:subs:pass-macro.adoc[inline pass macro].
The inline pass macro accepts a list of substitutions in the target slot, which can be used to control which substitutions are applied to the value.

In order for the inline macro to work in this context, it must completely surround the attribute value.
If it's used anywhere else in the value, it is ignored.

Here's how we can apply the xref:subs:quotes.adoc[quotes substitution] to the value of an attribute entry:

[source]
----
:app-name: pass:quotes[MyApp^2^]
----

Internally, the value is stored as `MyApp<sup>2</sup>`.
You can inspect the value stored in an attribute using this trick:

[source]
----
[subs=attributes+]
------
{app-name}
------
----

You can also specify the substitution using the single-character alias, `q`.

[source]
----
:app-name: pass:q[MyApp^2^]
----

The inline pass macro kind of works like an attribute value preprocessor.
If the processor detects that an inline pass macro completely surrounds the attribute value, it:

. reads the list of substitutions from the target slot of the macro
. unwraps the value from the macro
. applies the substitutions to the value

If the macro is absent, the value is processed with the header substitution group.

== Change substitutions when referencing an attribute

You can also change the substitutions that are applied to an attribute at the time it is resolved.
This is done by manipulating the substitutions applied to the text where it is referenced.
For example, here's how we could get the processor to apply quote substitutions to the value of an attribute:

[source]
----
:app-name: MyApp^2^

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
The application is called {app-name}.
----

Notice that we've swapped the order of the `attributes` and `quotes` substitutions.
This strategy is akin to post-processing the attribute value.
