= Inline Passthroughs
//um anchor: pass-macros

Asciidoctor supports several inline passthrough macros.

== Inline passthrough macros

single and double plus:: A special syntax for preventing text from being formatted.
Only escapes special characters for compliance with the output format and doesn't support explicit substitutions.

triple plus:: A special syntax for designating passthrough content.
Does not apply any substitutions (equivalent to the inline pass macro with no target) and doesn't support explicit substitutions.

inline pass macro:: An inline macro named `pass` that can be used to passthrough content.
Supports an optional set of substitutions.
+
[source]
----
pass:[content like #{variable} passed directly to the output] followed by normal content.

content with only select substitutions applied: pass:c,a[__<{email}>__]
----

TIP: When you need to prevent or control the substitutions on one or more blocks of content, use a xref:pass-block.adoc[delimited passthrough block or the pass block style].

== Triple plus macro

The triple plus passthrough excludes content enclosed in a set of triple pluses (pass:[+++]) from all substitutions.

 +++content passed directly to the output+++ followed by normal content.

The triple plus macro is often used to output custom HTML or XML.

[source]
----
include::example$pass.adoc[tag=3p]
----

====
include::example$pass.adoc[tag=3p]
====

[#pass-subs]
== Inline pass macro

To exclude inline content from substitutions and disable escaping of special characters, enclose it in the inline pass macro.
For example, here's one way to format text as underline when generating HTML from AsciiDoc:

[source]
----
include::example$pass.adoc[tag=in-macro]
----

====
include::example$pass.adoc[tag=in-macro]
====

WARNING: Using passthroughs to pass content (without substitutions) can couple your content to a specific output format, such as HTML.
In these cases, you should use conditional preprocessor directives to route passthrough content for different output formats based on the current backend.

== Nesting blocks and passthroughs

When you're using passthroughs inside literal and listing blocks, it can be easy to forget that the single plus and triple plus passthroughs are xref:macros.adoc[macros substitutions].
To enable the passthroughs, assign the `macros` value to the `subs` attribute.

....
[source,java,subs="+quotes,+macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/+++**+++").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
....

To learn more about applying substitutions to blocks, see xref:apply-subs-to-blocks.adoc[Customize the substitutions applied to blocks].

[source,java,subs="+quotes,+macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/+++**+++").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----

////
This content needs to be sorted and added to the deprecation and migration docs as needed.

CAUTION: Asciidoctor does not implement the block pass macro.
Instead, you should use a xref:pass-block.adoc[pass block].

double dollar (deprecated):: A deprecated special syntax for designating passthrough content.
Like the triple plus, does not apply any substitutions and doesn't support explicit substitutions.

.Double-dollar passthrough

The double-dollar passthrough behaves like the triple-plus passthrough, but it allows <<user-manual#special-characters,special characters>> in its content to be replaced.
Passthrough content is enclosed by double dollar signs (+$$+).

 $$Content passed directly to the output$$ followed by normal content.

[source]
----
include::ex-pass.adoc[tag=dollar]
----

====
include::ex-pass.adoc[tag=dollar]
====

[#back-pass]
.Backtick passthrough

Content enclosed in a backtick passthrough is subject to <<user-manual#special-characters,special characters>> substition and displayed as monospace text.

 `Content in a line that is passed directly to the output` followed by normal content.

Backticks (+`+) are commonly used around inline code containing markup.

[source]
----
include::ex-pass.adoc[tag=tick]
----

====
include::ex-pass.adoc[tag=tick]
====
////
