= Prevent Substitutions

Asciidoctor provides several approaches for preventing substitutions.

== Escape with a backslash

To prevent punctuation from being interpreted as formatting markup, precede it with a backslash (`\`).
If the formatting punctuation begins with two characters (e.g., `+__+`), you need to precede it with two backslashes (`+\\+`).
This is also how you can prevent character and attribute references from substitution.
When your document is processed, the backslash is removed so it doesn't display in your output.

[source]
----
include::example$subs.adoc[tag=slash]
----

== Passthroughs

The passthrough is the primary mechanism by which to escape content in AsciiDoc (far more comprehensive and consistent than using a backslash).
As the name implies, a passthrough passes content directly through to the output document without applying any substitutions.

You can also control and prevent substitutions in inline text with the xref:pass-macro.adoc[inline passthrough macros] and for entire blocks of content with the xref:pass-block.adoc[block passthrough].
Other forms of passthroughs, such as the single and double plus, apply substitutions strictly for compliance with the output format.
