= Character Replacement Substitutions
:y: Yes
//icon:check[role="green"]
:n: No
//icon:times[role="red"]
:url-html-ref: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
:url-unicode: https://en.wikipedia.org/wiki/List_of_Unicode_characters

The character replacement substitution step processes textual characters such as marks, arrows and dashes and replaces them with the decimal format of their Unicode code point, i.e., their <<char-ref-sidebar,numeric character reference>>.

// Table of Textual symbol replacements is inserted below
include::partial$subs-symbol-repl.adoc[]

WARNING: The `replacements` step depends on the substitutions completed by the `specialchars` step.
This is important to keep in mind when applying custom substitutions to a block.
See xref:apply-subs-to-blocks.adoc[Customize the substitutions applied to blocks] for more information.

This substitution step also recognizes {url-html-ref}[HTML and XML character references^] as well as {url-unicode}[decimal and hexadecimal Unicode code points^] and substitutes them for their corresponding decimal form Unicode code point.

For example, to produce the `&sect;` symbol you could write `\&sect;`, `\&#x00A7;`, or `\&#167;`.
When the document is processed, `replacements` will replace the section symbol reference, regardless of whether it is a named character reference or a numeric character reference, with `\&#167;`.
In turn, `\&#167;` will display as `&sect;`.

[#char-ref-sidebar]
.Anatomy of a character reference
****
A character reference is a standard sequence of characters that is substituted for a single character when Asciidoctor processes a document.
There are two types of character references: named character references and numeric character references.

A named character reference (often called a _character entity reference_) is a short name that refers to a character (i.e., glyph).
To make the reference, the name must be prefixed with an ampersand (`&`) and end with a semicolon (`;`).

For example:

* `\&dagger;` displays as &dagger;
* `\&euro;` displays as &euro;
* `\&loz;` displays as &loz;

Numeric character references are the decimal or hexadecimal Universal Character Set/Unicode code points which refer to a character.

* The decimal code point references are prefixed with an ampersand (`&`), followed by a hash (`&#35;`), and end with a semicolon (`;`).
* Hexadecimal code point references are prefixed with an ampersand (`&`), followed by a hash (`&#35;`), followed by a lowercase `x`, and end with a semicolon (`;`).

For example:

* `\&#x2020;` or `\&#8224;` displays as &#8224;
* `\&#x20AC;` or `\&#8364;` displays as &#8364;
* `\&#x25CA;` or `\&#9674;` displays as &#x25CA;

Developers may be more familiar with using *Unicode escape sequences* to perform text substitutions.
For example, to produce an `&#64;` sign using a Unicode escape sequence, you would prefix the hexadecimal Unicode code point with a backslash (`\`) and an uppercase or lowercase `u`, i.e. `u0040`.
However, Asciidoctor doesn't process and replace Unicode escape sequences at this time.
****

TIP: Asciidoctor also provides built-in attributes for representing some common symbols.
These attributes and their corresponding output are listed in the xref:attributes:ref-character-replacement.adoc[Character replacement attributes reference].

== Blocks and inline elements subject to the replacements substitution step

The `replacements` step occurs within title, paragraph, example, quote, sidebar, and verse blocks.

[width="60%", cols="3,^2"]
|===
|Blocks and elements |`replacements` applied

|Attribute entry values |{n}

|Comments |{n}

|Examples |{y}

|Headers |{n}

|Literal, listings, and source |{n}

|Macros (except passthroughs) |{y}

|Open |Varies

|Paragraphs |{y}

|Passthroughs |{n}

|Quotes and verses |{y}

|Sidebars |{y}

|Tables |Varies

|Titles |{y}
|===
