= Special Character Substitutions

The special characters substitution step (`specialchars`) searches for three characters (`<`, `>`, `&`) and replaces them with their xref:replacements.adoc#char-ref-sidebar[named character references].

* The less than symbol, `<`, is replaced with the named character reference `\&lt;`.
* The greater than symbol, `>`, is replaced with the named character reference `\&gt;`.
* An ampersand, `&`, is replaced with the named character reference `\&amp;`.

By default, the `specialchars` step occurs on all inline and block elements except for comments and certain passthroughs.
The substitution of special characters can be controlled on blocks using the xref:apply-subs-to-blocks.adoc[subs attribute] and on inline text using the xref:apply-subs-to-text.adoc[pass macro].

[NOTE]
====
Special character substitution precedes attribute substitution, so you will need to manually escape any attributes containing special characters that you set in the CLI or API.
For example, on the command line, type `-a toc-title="Sections, Tables \&amp; Figures"` instead of `-a toc-title="Sections, Tables & Figures"`.
====
