= Substitution Steps and Groups
:y: Yes
//icon:check[role="green"]
:n: No
//icon:times[role="red"]
////
user manual anchor: subs

This page needs to become a more user friendly overview of what substitutions can do, how to leverage them and how to escape them and/or prevent them with a pass through.

The groups and individual substitution categories (and tables) needs to be reorganized into a more cohesive body (and then squashed into a single reference page maybe?).
The apply, prevent, and control pages need to be organized into a logical flow with clear statements of ... I have this problem: I need to get this attribute reference in this block to be replaced by not have the other <whatever> replaced, what do I use?
All the groups and subs need to be hooked up to clear use cases.
The single plus macro has no explanation (at least not in this module).
The deprecate syntax needs to be moved to the deprecated table and/or migration docs.
////

== Substitution steps

The text substitution steps replace characters, markup, attribute references, and macros with the appropriate output for a given converter.
When a document is processed, up to six text substitution steps may be carried out depending on the block or inline element's assigned substitution group.
The processor runs the text substitution steps in the following order:

. xref:special-characters.adoc[Special characters]
. xref:quotes.adoc[Quotes (i.e., inline formatting)]
. xref:attributes.adoc[Attribute references]
. xref:replacements.adoc[Character replacements]
. xref:macros.adoc[Macros]
. xref:post-replacements.adoc[Post replacements]

These steps are organized into substitution groups.

[#substitution-groups]
== Substitution groups

Each block and inline element has a default substitution group that is applied unless you customize the substitution steps for a particular element.
The table below shows the substitution steps included in each group.

include::partial$subs-group-table.adoc[]

=== Normal substitution group

The `normal` substitution group is applied to the majority of the AsciiDoc block and inline elements except for those specific elements listed under the groups described in the next sections.

==== Title substitution group

The `title` substitution group includes the same substitutions as the `normal` group.
However, the order that the steps are executed is slightly different.
The steps are applied to titles in the following sequence:

. Special characters
. Quotes
. Character replacements
. Macros
. Attribute references
. Post replacements

=== Header substitution group

The `header` substitution group is applied to metadata lines (author and revision information) in the document header.
It's also applied to the values of attribute entries, regardless of whether those entries are defined in the document header or body.
Only special characters, attribute references, and the inline pass macro are replaced in elements that fall under the header group.

TIP: You can use the xref:apply-subs-to-text.adoc[inline pass macro] in attribute entries to customize the substitution steps applied to the attribute's value.

=== Verbatim substitution group

Literal, listing, and source blocks are processed using the `verbatim` substitution group.
Only special characters are replaced in these blocks.

=== Pass substitution group

The `pass` substitution group can only be applied to passthrough elements.
Attribute references and macros are replaced in passthroughs.

=== None substitution group

The `none` substitution group is applied to comment blocks.

== Escaping substitutions
// This paragraph is all new
Asciidoctor provides several approaches for preventing substitutions.
When you want to prevent punctuation and symbols from being interpreted as formatting markup, xref:prevent.adoc[escaping the punctuation with a backslash] may be sufficient.
For more comprehensive substitution prevention and control, you can use xref:pass-macro.adoc[inline passthrough macros] or xref:pass-block.adoc[passthrough blocks].
