= Add a Title to a Block
:xrefstyle: short
:listing-caption: Example

You can assign a title to a block, whether it's styled using its style name or delimiters.

== Block title syntax

A block title is defined on the line directly above the block's attribute list, opening delimiter, or block content--which ever comes first.
The line must begin with a dot (`.`) and immediately be followed by the text of the title.

[source]
----
.This is the title of a sidebar block
****
This is the content of the sidebar block.
****
----

The next sections will show you how to add titles to delimited blocks and blocks with attribute lists.

== Add a title to a delimited block

Any delimited block can have a title.
If the block doesn't have an attribute list, enter the title on a new line directly above the opening delimiter.
<<ex-1>> a delimited literal block has been titled _Terminal Output_.

[#ex-1]
.Add a title to a delimited literal block
[source]
----
.Terminal Output // <1>
.... // <2>
From github.com:asciidoctor/asciidoctor
 * branch        master   -> FETCH_HEAD
Already up to date.
....
----
. The block title is entered on a new line.
The title must begin with a dot (`.`).
Don't put a space between the dot and the first character of the title.
. If you aren't applying attributes to a block, enter the opening delimiter on a new line directly after the title.

.Result: Titled literal block
====
.Terminal Output
....
From github.com:asciidoctor/asciidoctor
 * branch        master   -> FETCH_HEAD
Already up to date.
....
====

In the next section, you'll see how a title can be place on a block that has attributes.

== Add a title to a block with attributes

When you're applying attributes to a block, the title is placed on the line above the attribute list (or lists).
<<ex-2>> shows a delimited source code block that's titled _Specify GitLab CI stages_.

[#ex-2]
.Add a title to a delimited source code block
[source]
....
.Specify GitLab CI stages  // <1>
[source,yaml] // <2>
----
image: node:10.16.3-buster
stages: [ init, verify, deploy ]
----
....
. The block title is entered on a new line.
. The block's attribute list is entered on a new line directly after the title.

.Rendered output of <<ex-2>>
====
[#ex-3]
.Specify GitLab CI stages
[source,yaml]
----
image: node:10.16.3-buster
stages: [ init, verify, deploy ]
----
====

As shown in <<ex-4>>, a block's title is placed above the attribute list when a block isn't delimited.

[#ex-4]
.Add a title to a non-delimited block
[source]
----
.Mint
[sidebar]
Mint has visions of global conquest.
If you don't plant it in a container, it will take over your garden.
----

.Result: Titled block with the sidebar style assigned
====
.Mint
[sidebar]
Mint has visions of global conquest.
If you don't plant it in a container, it will take over your garden.
====

You may notice that unlike the titles in the previous rendered listing and source block examples, the sidebar's title is centered and displayed inside the sidebar's background.
How the title of a block is displayed depends on the converter and stylesheet you're applying to your AsciiDoc documents.
