= Line and Page Breaks

[#hardbreaks]
== Line breaks

Since adjacent lines of text are combined into a single paragraph when Asciidoctor converts a document, that means you can wrap paragraph text or put each sentence or phrase on a separate line.
The line breaks won't appear in the output.

However, if you want the line breaks in a paragraph to be preserved, you can either use a space followed by a plus sign (`{plus}`) or the `hardbreaks` attribute.
This results in a visible line break (e.g., `<br>`) following each line.

[source]
.Line breaks preserved using a space followed by the plus sign ({plus})
----
include::example$paragraph.adoc[tag=hb]
----

====
include::example$paragraph.adoc[tag=hb]
====

[source]
.Line breaks preserved using the hardbreaks attribute
----
include::example$paragraph.adoc[tag=hb-p]
----

====
include::example$paragraph.adoc[tag=hb-p]
====

Alternatively, you can preserve line breaks throughout your whole document by adding the `hardbreaks` attribute to the document's header.

.Line breaks preserved throughout the document using the hardbreaks attribute
[source]
----
include::example$paragraph.adoc[tag=hb-attr]
----

You can also preserve line breaks using xref:source:literal.adoc[literal blocks], xref:source:listing.adoc[listing blocks], and xref:verse.adoc[verses].

== Page breaks

.Page break syntax
[source]
----
<<<
----
