= Source Code Blocks
:table-caption: Table
////
From user manual:
NOTE we really want this ID on the section, but there are problems w/ multiple IDs per section
[#source-code-blocks]
[#syntax-highlighting]
////

Developers are accustomed to seeing source code colorized to emphasize the code's structure (i.e., keywords, types, delimiters, etc.).
This technique is known as [.term]*syntax highlighting*.
Since this technique is so prevalent, Asciidoctor integrates with a number of libraries to syntax highlight the source code blocks in your document.
The list of integrated libraries includes Rouge, CodeRay, Pygments, highlight.js, and prettify.

<<ex-source>> shows a listing block with the `source` style and language `ruby` applied to its content.

.Source block syntax
[source#ex-source]
....
include::example$source.adoc[tag=src-base]
....

The result of <<ex-source>> is rendered below.

include::example$source.adoc[tag=src-base]

== Source highlighting

When enabled, source highlighting is applied to listing blocks and paragraphs that have the `source` style and a source language assigned to them.
You can define the source language directly on the block or globally using the `source-language` document attribute.

=== Enable source highlighting

Source highlighting isn't enabled by default.
To enable source highlighting in a document, you must set the `source-highlighter` document attribute.
You can set this attribute in the document header or from the CLI or API.

If you set the attribute in the document, it must be defined in the header using an attribute entry.

[source]
----
= Document Title
:source-highlighter: <value>
----

For example, here's how to enable syntax highlighting using Rouge:

[source]
----
= Document Title
:source-highlighter: rouge
----

=== Disable source highlighting

To disable source highlighting for a given source block, specify the language as `text` or remove the `source` style.

== Available source highlighters

<<table-highlighters>> lists the recognized values for the `source-highlighter` attribute and toolchains that support the usage of the syntax highlighting libraries.

.Built-in source-highlighter values and the supporting toolchains
[#table-highlighters%autowidth]
|===
|Library |Value |Toolchain

|{url-coderay}[CodeRay^]
|`coderay`
|Asciidoctor, AsciidoctorJ, Asciidoctor PDF

|{url-highlightjs}[highlight.js^]
|`highlightjs`
|Asciidoctor, AsciidoctorJ, Asciidoctor.js

|{url-prettify}[prettify^]
|`prettify`
|Asciidoctor, AsciidoctorJ, Asciidoctor.js

|{url-pygments}[Pygments^]
|`pygments`
|Asciidoctor, Asciidoctor PDF

|{url-rouge}[Rouge^]
|`rouge`
|Asciidoctor, AsciidoctorJ, Asciidoctor PDF
|===

[IMPORTANT]
====
To use Rouge, CodeRay, or Pygments, you must have the appropriate library installed on your system.
See xref:rouge.adoc[], xref:coderay.adoc[], or xref:pygments.adoc[] for installation instructions.

If you're using a client-side syntax highlighting library like xref:highlightjs.adoc[] or xref:prettify.adoc[], there's no need to install additional libraries.
The generated HTML will load the required source files from a CDN, custom URL, or file path.
====

.Source Highlighter vs. Syntax Highlighter
****
You might notice that the `source-highlighter` attribute uses the term "`source highlighter`", whereas the library that performs the highlighting is referred to as a "`syntax highlighter`".
What's the difference?

* The generally accepted term for a syntax (aka code) highlighter is "`syntax highlighter`".
* The syntax highlighter is applied to source blocks in AsciiDoc, hence why we say "`source highlighter`".

In other words, the `source-highlighter` attribute means "`use this syntax highlighter to colorize source blocks`".
****

== Apply source highlighting

To apply highlighting to source code, you must add the `source` style to a listing block, literal block, or paragraph and specify a source language.

.Code block with title and syntax highlighting
[listing#ex-code]
....
include::example$source.adoc[tag=src-base-co]
....
. Assign the block style `source` to the first position in the attribute list.
. An optional ID can be added to the block by appending it to style using the shorthand syntax (`#`) for `id`.
. Assign a source language to the second position.
. The source style is typically assigned to delimited listing and literal blocks.

The result of <<ex-code>> is displayed below.

include::example$source.adoc[tag=src-base-co-res]

.Source style
[source#ex-style]
----
include::example$source.adoc[tag=src-para-co]
----
. Place the attribute list directly on the paragraph.
. Once an empty line is encountered the syntax highlighting is unset.

The result of <<ex-style>> is displayed below.

include::example$source.adoc[tag=src-para]

== source-language attribute syntax

If the majority of your source blocks use the same source language, you can set the `source-language` attribute in the document header and assign a language to it.

.Set source-language attribute
[listing#ex-language]
....
include::example$source.adoc[tag=src-lang]
....

You can override the global source language on an individual block by specifying a source language after `source`.

.Override source-language attribute
[listing#ex-override]
....
include::example$source.adoc[tag=override]
....

== Using include directives in source blocks

You can use an xref:directives:include-directives.adoc[include directive] to insert source code into an AsciiDoc document directly from a file.

.Code block inserted from another file
[listing#ex-include]
....
include::example$source.adoc[tag=src-inc]
....

//TODO mention the use of AsciiDoc tags to include code snippets and the indent flag to reset indentation

TIP: If you specify custom substitutions on the source block using the `subs` attribute, make sure to include the `specialcharacters` substitution if you want to preserve syntax highlighting.
However, if you do plan to modify the substitutions, we recommend using xref:subs:apply-subs-to-blocks.adoc#incremental[incremental substitutions] instead.

// Highlight PHP sidebar was taken from end of page and made its own page
